requester:
  queue-prefix: __myQueueTest15__
  redrive: true

server.port: 0

management.endpoints.web.exposure.include: shutdown,health
management.endpoint.shutdown.enabled: true
endpoints.shutdown.enabled: true
